{
 "title": "Zammad: Rating System",
 "description": "Sample dashboard for Zammad Agents Rating System.",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval_graphs", "label": "Graph Intervall", "query": "1h,1d,2d,7d,30d" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Agents Rating", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rating: Agent Name 2",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rate.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      },
      {
       "field": "owner.fullname.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "state.name.keyword:\"closed\" AND NOT owner.fullname.keyword:\"-\" AND owner.fullname.keyword:\"Agent Name 2\" AND NOT rate.keyword:\"\"",
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Rating: Agent Name",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rate.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      },
      {
       "field": "owner.fullname.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "state.name.keyword:\"closed\" AND NOT owner.fullname.keyword:\"-\" AND owner.fullname.keyword:\"Agent Name\" AND NOT rate.keyword:\"\"",
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Rating: Agent Name 3",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rate.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      },
      {
       "field": "owner.fullname.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "state.name.keyword:\"closed\" AND NOT owner.fullname.keyword:\"-\" AND owner.fullname.keyword:\"Agent Name 3\" AND NOT rate.keyword:\"\"",
     "timeField": "created_at"
    }
   ]
  }
 ]
}